#!/usr/bin/env python3
import sys

# Rewrite of blk_analyse

from libbta.config import Config
from libbta.parser import parser_babeltrace as traceparser

if __name__ == '__main__':
    config = Config()
    config.parse_args()
