#!/usr/bin/env python3
import sys
import time

# Rewrite of blk_analyse

from libbta.config import Config
from libbta.sorter import Sorter

if __name__ == '__main__':
    start = time.time()
    config = Config()
    config.parse_args()
    print(time.time()-start)

    if config.args.action == 'list-events':
        for e in config.events:
            print(e)
    else:
        start = time.time()
        sorter = Sorter(config.layermaps)
        sorter.read_events(config.events)
        print(time.time()-start)
